"""Создание таблиц welders, installers, organizations

Revision ID: 0ecb5e46b98d
Revises: 
Create Date: 2025-04-13 22:34:04.311196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ecb5e46b98d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installers', sa.Column('surname', sa.String(), nullable=False))
    op.add_column('installers', sa.Column('patronymic', sa.String(), nullable=True))
    op.add_column('welders', sa.Column('surname', sa.String(), nullable=False))
    op.add_column('welders', sa.Column('patronymic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('welders', 'patronymic')
    op.drop_column('welders', 'surname')
    op.drop_column('installers', 'patronymic')
    op.drop_column('installers', 'surname')
    # ### end Alembic commands ###
