"""add_photo

Revision ID: d73636c77e5d
Revises: ff20d9d9625c
Create Date: 2025-04-17 14:44:14.873076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd73636c77e5d'
down_revision: Union[str, None] = 'ff20d9d9625c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('installers', 'photo_path')
    op.drop_column('welders', 'photo_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('welders', sa.Column('photo_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('installers', sa.Column('photo_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
