"""Initial migration

Revision ID: ff20d9d9625c
Revises: 0ecb5e46b98d
Create Date: 2025-04-17 14:15:24.587821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff20d9d9625c'
down_revision: Union[str, None] = '0ecb5e46b98d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installers', sa.Column('photo_id', sa.String(), nullable=True))
    op.add_column('welders', sa.Column('photo_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('welders', 'photo_id')
    op.drop_column('installers', 'photo_id')
    # ### end Alembic commands ###
